services:
  node:
    image: mofosio-backend:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - APP_PORT=${APP_PORT:-3000}
    container_name: node
    env_file:
      - .env
    ports:
      - "${APP_PORT:-3000}:${APP_PORT:-3000}"
    healthcheck:
      test:  wget --spider -q http://localhost:${APP_PORT:-3000}/healthz
      interval: 10s
      timeout: 5s
      retries: 3